### ISSUE TITLE
三角面片为什么取的是边的中点？

### ISSUE THREAD

**Issue by NingMYZZ** [CHINA-JIGE/MarchingCube#2]
为什么三角面片要取边的中点呀，有的时候三角面片是包含顶点的。` mMeshOutput.push_back(pointOnEdge[triCase.index[i]] - VECTOR3(BigCubeWidth0.5f, BigCubeHeight0.5f, BigCubeDepth*0.5f)); `

**Comment by CHINA-JIGE** [comment]
取中点是这个：VECTOR3 pointOnEdge[12] =
				{
					(v[0] + v[1]) * 0.5f,
					(v[1] + v[2]) * 0.5f,
					(v[3] + v[2]) * 0.5f,
					(v[0] + v[3]) * 0.5f,
					(v[4] + v[5]) * 0.5f,
					(v[5] + v[6]) * 0.5f,
					(v[7] + v[6]) * 0.5f,
					(v[4] + v[7]) * 0.5f,
					(v[0] + v[4]) * 0.5f,
					(v[1] + v[5]) * 0.5f,
					(v[3] + v[7]) * 0.5f,
					(v[2] + v[6]) * 0.5f
};
其次，其实讲道理是可以不取棱的中点的，可以取棱上的某一点，不过这个线性插值的系数t \in [0,1]在这个小项目里面不好求（因为都是二值化的体素值）。如果有更高精度的标量场描述，就不一定是中点了，因为棱上取的顶点最好也是在等值面（曲面）上。

**Comment by NingMYZZ** [comment]
好的，我理解了你的意思，谢谢！

**Comment by NingMYZZ** [comment]
额，我搞错了一个地方，谢谢！
