### ISSUE TITLE
请问从体素用marching cube生成模型难么？

### ISSUE THREAD

**Issue by lixz123007** [CHINA-JIGE/MarchingCube#9]
老哥，我是搞3D重建的tsdf，现在一直是用ubuntu的C++程序生成体素.bin，文件扔到matlab里用isosurface函数，重建。现在想把matlab这一步整合到c++里，看到了marching cube这个东西，请问从体素信息重建写个ubuntu的C++的marching cube函数难不难？老哥有知道有没有类似的现成代码，或者有啥论文教程推荐？
感激不尽!

**Comment by CHINA-JIGE** [comment]
那我这个repo不就是marching cube吗。。。
